<?php
/**
 * ConstructionSubmitRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\rosettaserverstubs\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace melmccann\rosettaserverstubs\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ConstructionSubmitRequest model.
 *
 * The transaction submission request includes a signed transaction.
 *
 * @package melmccann\rosettaserverstubs\Model
 * @author  OpenAPI Generator team
 */
class ConstructionSubmitRequest 
{
        /**
     * @var melmccann\rosettaserverstubs\Model\NetworkIdentifier
     * @SerializedName("network_identifier")
     * @Assert\NotNull()
     * @Assert\Type("melmccann\rosettaserverstubs\Model\NetworkIdentifier")
     * @Type("melmccann\rosettaserverstubs\Model\NetworkIdentifier")
     */
    protected $networkIdentifier;

    /**
     * @var string
     * @SerializedName("signed_transaction")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $signedTransaction;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->networkIdentifier = isset($data['networkIdentifier']) ? $data['networkIdentifier'] : null;
        $this->signedTransaction = isset($data['signedTransaction']) ? $data['signedTransaction'] : null;
    }

    /**
     * Gets networkIdentifier.
     *
     * @return melmccann\rosettaserverstubs\Model\NetworkIdentifier
     */
    public function getNetworkIdentifier(): NetworkIdentifier
    {
        return $this->networkIdentifier;
    }

    /**
     * Sets networkIdentifier.
     *
     * @param melmccann\rosettaserverstubs\Model\NetworkIdentifier $networkIdentifier
     *
     * @return $this
     */
    public function setNetworkIdentifier(NetworkIdentifier $networkIdentifier): NetworkIdentifier
    {
        $this->networkIdentifier = $networkIdentifier;

        return $this;
    }

    /**
     * Gets signedTransaction.
     *
     * @return string
     */
    public function getSignedTransaction()
    {
        return $this->signedTransaction;
    }

    /**
     * Sets signedTransaction.
     *
     * @param string $signedTransaction
     *
     * @return $this
     */
    public function setSignedTransaction($signedTransaction)
    {
        $this->signedTransaction = $signedTransaction;

        return $this;
    }
}


