<?php
/**
 * NetworkListResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\rosettaserverstubs\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace melmccann\rosettaserverstubs\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the NetworkListResponse model.
 *
 * A NetworkListResponse contains all NetworkIdentifiers that the node can serve information for.
 *
 * @package melmccann\rosettaserverstubs\Model
 * @author  OpenAPI Generator team
 */
class NetworkListResponse 
{
        /**
     * @var melmccann\rosettaserverstubs\Model\NetworkIdentifier[]
     * @SerializedName("network_identifiers")
     * @Assert\NotNull()
     * @Assert\All({
     *   @Assert\Type("melmccann\rosettaserverstubs\Model\NetworkIdentifier")
     * })
     * @Type("array<melmccann\rosettaserverstubs\Model\NetworkIdentifier>")
     */
    protected $networkIdentifiers;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->networkIdentifiers = isset($data['networkIdentifiers']) ? $data['networkIdentifiers'] : null;
    }

    /**
     * Gets networkIdentifiers.
     *
     * @return melmccann\rosettaserverstubs\Model\NetworkIdentifier[]
     */
    public function getNetworkIdentifiers(): array
    {
        return $this->networkIdentifiers;
    }

    /**
     * Sets networkIdentifiers.
     *
     * @param melmccann\rosettaserverstubs\Model\NetworkIdentifier[] $networkIdentifiers
     *
     * @return $this
     */
    public function setNetworkIdentifiers(array $networkIdentifiers)
    {
        $this->networkIdentifiers = $networkIdentifiers;

        return $this;
    }
}


