<?php
/**
 * AccountBalanceRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\rosettaserverstubs\RosettaServerStubsModel
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace melmccann\rosettaserverstubs\RosettaServerStubsModel;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the AccountBalanceRequest model.
 *
 * An AccountBalanceRequest is utilized to make a balance request on the /account/balance endpoint. If the block_identifier is populated, a historical balance query should be performed.
 *
 * @package melmccann\rosettaserverstubs\RosettaServerStubsModel
 * @author  OpenAPI Generator team
 */
class AccountBalanceRequest 
{
        /**
     * @var melmccann\rosettaserverstubs\RosettaServerStubsModel\NetworkIdentifier
     * @SerializedName("network_identifier")
     * @Assert\NotNull()
     * @Assert\Type("melmccann\rosettaserverstubs\RosettaServerStubsModel\NetworkIdentifier")
     * @Type("melmccann\rosettaserverstubs\RosettaServerStubsModel\NetworkIdentifier")
     */
    protected $networkIdentifier;

    /**
     * @var melmccann\rosettaserverstubs\RosettaServerStubsModel\AccountIdentifier
     * @SerializedName("account_identifier")
     * @Assert\NotNull()
     * @Assert\Type("melmccann\rosettaserverstubs\RosettaServerStubsModel\AccountIdentifier")
     * @Type("melmccann\rosettaserverstubs\RosettaServerStubsModel\AccountIdentifier")
     */
    protected $accountIdentifier;

    /**
     * @var melmccann\rosettaserverstubs\RosettaServerStubsModel\PartialBlockIdentifier|null
     * @SerializedName("block_identifier")
     * @Assert\Type("melmccann\rosettaserverstubs\RosettaServerStubsModel\PartialBlockIdentifier")
     * @Type("melmccann\rosettaserverstubs\RosettaServerStubsModel\PartialBlockIdentifier")
     */
    protected $blockIdentifier;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->networkIdentifier = isset($data['networkIdentifier']) ? $data['networkIdentifier'] : null;
        $this->accountIdentifier = isset($data['accountIdentifier']) ? $data['accountIdentifier'] : null;
        $this->blockIdentifier = isset($data['blockIdentifier']) ? $data['blockIdentifier'] : null;
    }

    /**
     * Gets networkIdentifier.
     *
     * @return melmccann\rosettaserverstubs\RosettaServerStubsModel\NetworkIdentifier
     */
    public function getNetworkIdentifier(): NetworkIdentifier
    {
        return $this->networkIdentifier;
    }

    /**
     * Sets networkIdentifier.
     *
     * @param melmccann\rosettaserverstubs\RosettaServerStubsModel\NetworkIdentifier $networkIdentifier
     *
     * @return $this
     */
    public function setNetworkIdentifier(NetworkIdentifier $networkIdentifier): NetworkIdentifier
    {
        $this->networkIdentifier = $networkIdentifier;

        return $this;
    }

    /**
     * Gets accountIdentifier.
     *
     * @return melmccann\rosettaserverstubs\RosettaServerStubsModel\AccountIdentifier
     */
    public function getAccountIdentifier(): AccountIdentifier
    {
        return $this->accountIdentifier;
    }

    /**
     * Sets accountIdentifier.
     *
     * @param melmccann\rosettaserverstubs\RosettaServerStubsModel\AccountIdentifier $accountIdentifier
     *
     * @return $this
     */
    public function setAccountIdentifier(AccountIdentifier $accountIdentifier): AccountIdentifier
    {
        $this->accountIdentifier = $accountIdentifier;

        return $this;
    }

    /**
     * Gets blockIdentifier.
     *
     * @return melmccann\rosettaserverstubs\RosettaServerStubsModel\PartialBlockIdentifier|null
     */
    public function getBlockIdentifier(): ?PartialBlockIdentifier
    {
        return $this->blockIdentifier;
    }

    /**
     * Sets blockIdentifier.
     *
     * @param melmccann\rosettaserverstubs\RosettaServerStubsModel\PartialBlockIdentifier|null $blockIdentifier
     *
     * @return $this
     */
    public function setBlockIdentifier(PartialBlockIdentifier $blockIdentifier = null): ?PartialBlockIdentifier
    {
        $this->blockIdentifier = $blockIdentifier;

        return $this;
    }
}


