<?php
/**
 * NetworkOptionsResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\rosettaserverstubs\RosettaServerStubsModel
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace melmccann\rosettaserverstubs\RosettaServerStubsModel;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the NetworkOptionsResponse model.
 *
 * NetworkOptionsResponse contains information about the versioning of the node and the allowed operation statuses, operation types, and errors.
 *
 * @package melmccann\rosettaserverstubs\RosettaServerStubsModel
 * @author  OpenAPI Generator team
 */
class NetworkOptionsResponse 
{
        /**
     * @var melmccann\rosettaserverstubs\RosettaServerStubsModel\Version
     * @SerializedName("version")
     * @Assert\NotNull()
     * @Assert\Type("melmccann\rosettaserverstubs\RosettaServerStubsModel\Version")
     * @Type("melmccann\rosettaserverstubs\RosettaServerStubsModel\Version")
     */
    protected $version;

    /**
     * @var melmccann\rosettaserverstubs\RosettaServerStubsModel\Allow
     * @SerializedName("allow")
     * @Assert\NotNull()
     * @Assert\Type("melmccann\rosettaserverstubs\RosettaServerStubsModel\Allow")
     * @Type("melmccann\rosettaserverstubs\RosettaServerStubsModel\Allow")
     */
    protected $allow;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->version = isset($data['version']) ? $data['version'] : null;
        $this->allow = isset($data['allow']) ? $data['allow'] : null;
    }

    /**
     * Gets version.
     *
     * @return melmccann\rosettaserverstubs\RosettaServerStubsModel\Version
     */
    public function getVersion(): Version
    {
        return $this->version;
    }

    /**
     * Sets version.
     *
     * @param melmccann\rosettaserverstubs\RosettaServerStubsModel\Version $version
     *
     * @return $this
     */
    public function setVersion(Version $version): Version
    {
        $this->version = $version;

        return $this;
    }

    /**
     * Gets allow.
     *
     * @return melmccann\rosettaserverstubs\RosettaServerStubsModel\Allow
     */
    public function getAllow(): Allow
    {
        return $this->allow;
    }

    /**
     * Sets allow.
     *
     * @param melmccann\rosettaserverstubs\RosettaServerStubsModel\Allow $allow
     *
     * @return $this
     */
    public function setAllow(Allow $allow): Allow
    {
        $this->allow = $allow;

        return $this;
    }
}


