<?php
/**
 * ConstructionApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\rosettaserverstubs
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace melmccann\rosettaserverstubs\melmccann\rosetta-server-stubs;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use melmccann\rosettaserverstubs\RosettaServerStubsModel\ConstructionMetadataRequest;
use melmccann\rosettaserverstubs\RosettaServerStubsModel\ConstructionMetadataResponse;
use melmccann\rosettaserverstubs\RosettaServerStubsModel\ConstructionSubmitRequest;
use melmccann\rosettaserverstubs\RosettaServerStubsModel\ConstructionSubmitResponse;
use melmccann\rosettaserverstubs\RosettaServerStubsModel\Error;

/**
 * ConstructionApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  melmccann\rosettaserverstubs\melmccann\rosetta-server-stubs
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface ConstructionApiInterface
{

    /**
     * Operation constructionMetadata
     *
     * Get Transaction Construction Metadata
     *
     * @param  melmccann\rosettaserverstubs\RosettaServerStubsModel\ConstructionMetadataRequest $constructionMetadataRequest   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return melmccann\rosettaserverstubs\RosettaServerStubsModel\ConstructionMetadataResponse
     *
     */
    public function constructionMetadata(ConstructionMetadataRequest $constructionMetadataRequest, &$responseCode, array &$responseHeaders);

    /**
     * Operation constructionSubmit
     *
     * Submit a Signed Transaction
     *
     * @param  melmccann\rosettaserverstubs\RosettaServerStubsModel\ConstructionSubmitRequest $constructionSubmitRequest   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return melmccann\rosettaserverstubs\RosettaServerStubsModel\ConstructionSubmitResponse
     *
     */
    public function constructionSubmit(ConstructionSubmitRequest $constructionSubmitRequest, &$responseCode, array &$responseHeaders);
}
