<?php
/**
 * AccountBalanceRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccannosettaserverstubs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace melmccannosettaserverstubs\RosettaServerStubsModel;

use \ArrayAccess;
use \melmccannosettaserverstubs\ObjectSerializer;

/**
 * AccountBalanceRequest Class Doc Comment
 *
 * @category Class
 * @description An AccountBalanceRequest is utilized to make a balance request on the /account/balance endpoint. If the block_identifier is populated, a historical balance query should be performed.
 * @package  melmccannosettaserverstubs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountBalanceRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AccountBalanceRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'network_identifier' => '\melmccannosettaserverstubs\RosettaServerStubsModel\NetworkIdentifier',
        'account_identifier' => '\melmccannosettaserverstubs\RosettaServerStubsModel\AccountIdentifier',
        'block_identifier' => '\melmccannosettaserverstubs\RosettaServerStubsModel\PartialBlockIdentifier'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'network_identifier' => null,
        'account_identifier' => null,
        'block_identifier' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'network_identifier' => 'network_identifier',
        'account_identifier' => 'account_identifier',
        'block_identifier' => 'block_identifier'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'network_identifier' => 'setNetworkIdentifier',
        'account_identifier' => 'setAccountIdentifier',
        'block_identifier' => 'setBlockIdentifier'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'network_identifier' => 'getNetworkIdentifier',
        'account_identifier' => 'getAccountIdentifier',
        'block_identifier' => 'getBlockIdentifier'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['network_identifier'] = isset($data['network_identifier']) ? $data['network_identifier'] : null;
        $this->container['account_identifier'] = isset($data['account_identifier']) ? $data['account_identifier'] : null;
        $this->container['block_identifier'] = isset($data['block_identifier']) ? $data['block_identifier'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['network_identifier'] === null) {
            $invalidProperties[] = "'network_identifier' can't be null";
        }
        if ($this->container['account_identifier'] === null) {
            $invalidProperties[] = "'account_identifier' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets network_identifier
     *
     * @return \melmccannosettaserverstubs\RosettaServerStubsModel\NetworkIdentifier
     */
    public function getNetworkIdentifier()
    {
        return $this->container['network_identifier'];
    }

    /**
     * Sets network_identifier
     *
     * @param \melmccannosettaserverstubs\RosettaServerStubsModel\NetworkIdentifier $network_identifier network_identifier
     *
     * @return $this
     */
    public function setNetworkIdentifier($network_identifier)
    {
        $this->container['network_identifier'] = $network_identifier;

        return $this;
    }

    /**
     * Gets account_identifier
     *
     * @return \melmccannosettaserverstubs\RosettaServerStubsModel\AccountIdentifier
     */
    public function getAccountIdentifier()
    {
        return $this->container['account_identifier'];
    }

    /**
     * Sets account_identifier
     *
     * @param \melmccannosettaserverstubs\RosettaServerStubsModel\AccountIdentifier $account_identifier account_identifier
     *
     * @return $this
     */
    public function setAccountIdentifier($account_identifier)
    {
        $this->container['account_identifier'] = $account_identifier;

        return $this;
    }

    /**
     * Gets block_identifier
     *
     * @return \melmccannosettaserverstubs\RosettaServerStubsModel\PartialBlockIdentifier|null
     */
    public function getBlockIdentifier()
    {
        return $this->container['block_identifier'];
    }

    /**
     * Sets block_identifier
     *
     * @param \melmccannosettaserverstubs\RosettaServerStubsModel\PartialBlockIdentifier|null $block_identifier block_identifier
     *
     * @return $this
     */
    public function setBlockIdentifier($block_identifier)
    {
        $this->container['block_identifier'] = $block_identifier;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


