<?php
/**
 * AccountBalanceRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\rosettaserverstubs\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace melmccann\rosettaserverstubs\Model;

/**
 * AccountBalanceRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description An AccountBalanceRequest is utilized to make a balance request on the /account/balance endpoint. If the block_identifier is populated, a historical balance query should be performed.
/**
 * @package     melmccann\rosettaserverstubs\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class AccountBalanceRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountBalanceRequest"
     */
    public function testAccountBalanceRequest()
    {
        $testAccountBalanceRequest = new AccountBalanceRequest();
    }

    /**
     * Test attribute "networkIdentifier"
     */
    public function testPropertyNetworkIdentifier()
    {
    }

    /**
     * Test attribute "accountIdentifier"
     */
    public function testPropertyAccountIdentifier()
    {
    }

    /**
     * Test attribute "blockIdentifier"
     */
    public function testPropertyBlockIdentifier()
    {
    }
}
