<?php
/**
 * NetworkStatusResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

/**
 * NetworkStatusResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description NetworkStatusResponse contains basic information about the node&#39;s view of a blockchain network.
/**
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class NetworkStatusResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NetworkStatusResponse"
     */
    public function testNetworkStatusResponse()
    {
        $testNetworkStatusResponse = new NetworkStatusResponse();
    }

    /**
     * Test attribute "currentBlockIdentifier"
     */
    public function testPropertyCurrentBlockIdentifier()
    {
    }

    /**
     * Test attribute "currentBlockTimestamp"
     */
    public function testPropertyCurrentBlockTimestamp()
    {
    }

    /**
     * Test attribute "genesisBlockIdentifier"
     */
    public function testPropertyGenesisBlockIdentifier()
    {
    }

    /**
     * Test attribute "peers"
     */
    public function testPropertyPeers()
    {
    }
}
