<?php
/**
 * TransactionIdentifierTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\rosettaserverstubs\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace melmccann\rosettaserverstubs\RosettaServerStubsModel;

/**
 * TransactionIdentifierTest Class Doc Comment
 *
 * @category    Class */
// * @description The transaction_identifier uniquely identifies a transaction in a particular network and block or in the mempool.
/**
 * @package     melmccann\rosettaserverstubs\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class TransactionIdentifierTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransactionIdentifier"
     */
    public function testTransactionIdentifier()
    {
        $testTransactionIdentifier = new TransactionIdentifier();
    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {
    }
}
