<?php
/**
 * ConstructionSubmitRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccannosettaserverstubs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace melmccannosettaserverstubs;

use PHPUnit\Framework\TestCase;

/**
 * ConstructionSubmitRequestTest Class Doc Comment
 *
 * @category    Class
 * @description The transaction submission request includes a signed transaction.
 * @package     melmccannosettaserverstubs
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ConstructionSubmitRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConstructionSubmitRequest"
     */
    public function testConstructionSubmitRequest()
    {
    }

    /**
     * Test attribute "network_identifier"
     */
    public function testPropertyNetworkIdentifier()
    {
    }

    /**
     * Test attribute "signed_transaction"
     */
    public function testPropertySignedTransaction()
    {
    }
}
