<?php
/**
 * NetworkIdentifierTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccannosettaserverstubs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace melmccannosettaserverstubs;

use PHPUnit\Framework\TestCase;

/**
 * NetworkIdentifierTest Class Doc Comment
 *
 * @category    Class
 * @description The network_identifier specifies which network a particular object is associated with.
 * @package     melmccannosettaserverstubs
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class NetworkIdentifierTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NetworkIdentifier"
     */
    public function testNetworkIdentifier()
    {
    }

    /**
     * Test attribute "blockchain"
     */
    public function testPropertyBlockchain()
    {
    }

    /**
     * Test attribute "network"
     */
    public function testPropertyNetwork()
    {
    }

    /**
     * Test attribute "sub_network_identifier"
     */
    public function testPropertySubNetworkIdentifier()
    {
    }
}
