<?php
/**
 * PeerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  melmccannosettaserverstubs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace melmccannosettaserverstubs;

use PHPUnit\Framework\TestCase;

/**
 * PeerTest Class Doc Comment
 *
 * @category    Class
 * @description A Peer is a representation of a node&#39;s peer.
 * @package     melmccannosettaserverstubs
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PeerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Peer"
     */
    public function testPeer()
    {
    }

    /**
     * Test attribute "peer_id"
     */
    public function testPropertyPeerId()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }
}
