<?php
/**
 * AccountApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\rosettaserverstubs
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace melmccann\rosettaserverstubs\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use melmccann\rosettaserverstubs\Model\AccountBalanceRequest;
use melmccann\rosettaserverstubs\Model\AccountBalanceResponse;
use melmccann\rosettaserverstubs\Model\Error;

/**
 * AccountApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  melmccann\rosettaserverstubs\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface AccountApiInterface
{

    /**
     * Operation accountBalance
     *
     * Get an Account Balance
     *
     * @param  melmccann\rosettaserverstubs\Model\AccountBalanceRequest $accountBalanceRequest   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return melmccann\rosettaserverstubs\Model\AccountBalanceResponse
     *
     */
    public function accountBalance(AccountBalanceRequest $accountBalanceRequest, &$responseCode, array &$responseHeaders);
}
