<?php
/**
 * ConstructionApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\ConstructionMetadataRequest;
use OpenAPI\Server\Model\ConstructionMetadataResponse;
use OpenAPI\Server\Model\ConstructionSubmitRequest;
use OpenAPI\Server\Model\ConstructionSubmitResponse;
use OpenAPI\Server\Model\Error;

/**
 * ConstructionApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface ConstructionApiInterface
{

    /**
     * Operation constructionMetadata
     *
     * Get Transaction Construction Metadata
     *
     * @param  OpenAPI\Server\Model\ConstructionMetadataRequest $constructionMetadataRequest   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ConstructionMetadataResponse
     *
     */
    public function constructionMetadata(ConstructionMetadataRequest $constructionMetadataRequest, &$responseCode, array &$responseHeaders);

    /**
     * Operation constructionSubmit
     *
     * Submit a Signed Transaction
     *
     * @param  OpenAPI\Server\Model\ConstructionSubmitRequest $constructionSubmitRequest   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ConstructionSubmitResponse
     *
     */
    public function constructionSubmit(ConstructionSubmitRequest $constructionSubmitRequest, &$responseCode, array &$responseHeaders);
}
