<?php
/**
 * NetworkApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  melmccann\rosettaserverstubs
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Rosetta
 *
 * A Standard for Blockchain Interaction
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace melmccann\rosettaserverstubs\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use melmccann\rosettaserverstubs\Model\Error;
use melmccann\rosettaserverstubs\Model\MetadataRequest;
use melmccann\rosettaserverstubs\Model\NetworkListResponse;
use melmccann\rosettaserverstubs\Model\NetworkOptionsResponse;
use melmccann\rosettaserverstubs\Model\NetworkRequest;
use melmccann\rosettaserverstubs\Model\NetworkStatusResponse;

/**
 * NetworkApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  melmccann\rosettaserverstubs\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface NetworkApiInterface
{

    /**
     * Operation networkList
     *
     * Get List of Available Networks
     *
     * @param  melmccann\rosettaserverstubs\Model\MetadataRequest $metadataRequest   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return melmccann\rosettaserverstubs\Model\NetworkListResponse
     *
     */
    public function networkList(MetadataRequest $metadataRequest, &$responseCode, array &$responseHeaders);

    /**
     * Operation networkOptions
     *
     * Get Network Options
     *
     * @param  melmccann\rosettaserverstubs\Model\NetworkRequest $networkRequest   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return melmccann\rosettaserverstubs\Model\NetworkOptionsResponse
     *
     */
    public function networkOptions(NetworkRequest $networkRequest, &$responseCode, array &$responseHeaders);

    /**
     * Operation networkStatus
     *
     * Get Network Status
     *
     * @param  melmccann\rosettaserverstubs\Model\NetworkRequest $networkRequest   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return melmccann\rosettaserverstubs\Model\NetworkStatusResponse
     *
     */
    public function networkStatus(NetworkRequest $networkRequest, &$responseCode, array &$responseHeaders);
}
